# Generated by Django 5.1.6 on 2025-02-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('public_key', models.CharField(max_length=130)),
                ('verification_start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('success_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
