# Generated by Django 5.1.6 on 2025-03-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_verify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='public_key',
            field=models.CharField(max_length=66),
        ),
    ]
