# Generated by Django 5.1.6 on 2025-03-11 14:44

import apps.device_verify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_verify', '0002_alter_device_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.CharField(max_length=32, unique=True, validators=[apps.device_verify.models.validate_uid]),
        ),
    ]
