# Generated by Django 5.1.6 on 2025-03-12 17:11

import apps.device_verify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_verify', '0005_alter_device_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='public_key',
            field=models.CharField(max_length=66, unique=True, validators=[apps.device_verify.models.validate_public_key]),
        ),
    ]
