# Generated by Django 5.1.7 on 2025-07-29 18:34

import apps.device_verify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_verify', '0006_alter_device_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='success_counter',
            field=models.IntegerField(default=0, verbose_name='Counter'),
        ),
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.CharField(max_length=32, unique=True, validators=[apps.device_verify.models.validate_uid], verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='verification_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='First verification'),
        ),
    ]
