# Generated by Django 5.1.7 on 2025-10-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=200, verbose_name='Campaign name')),
                ('redeem_code', models.CharField(max_length=32, unique=True, verbose_name='Redeem code')),
                ('redemption_address_type', models.IntegerField(verbose_name='Redemption address type')),
                ('redemption_state', models.BooleanField(default=False, verbose_name='Redeemed')),
                ('redemption_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Redemption date')),
            ],
        ),
    ]
