# Generated by Django 5.1.7 on 2025-10-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeem_codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeem',
            name='redeem_code',
            field=models.CharField(blank=True, max_length=32, unique=True, verbose_name='Redeem code'),
        ),
    ]
