# Generated by Django 5.1.7 on 2025-10-20 06:25

import apps.redeem_codes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeem_codes', '0002_alter_redeem_redeem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeem',
            name='campaign_name',
            field=models.CharField(max_length=200, validators=[apps.redeem_codes.models.validate_campaign_name], verbose_name='Campaign name'),
        ),
        migrations.AlterField(
            model_name='redeem',
            name='redeem_code',
            field=models.CharField(blank=True, max_length=48, unique=True, verbose_name='Redeem code'),
        ),
    ]
