# Generated by Django 5.1.7 on 2025-10-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redeem_codes', '0003_alter_redeem_campaign_name_alter_redeem_redeem_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redeem',
            options={'verbose_name': 'Redeem Campaign', 'verbose_name_plural': 'Redeem Campaigns'},
        ),
    ]
