# Generated by Django 5.1.7 on 2025-10-21 07:17

import apps.redeem_codes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeem_codes', '0004_alter_redeem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=200, validators=[apps.redeem_codes.models.validate_campaign_name], verbose_name='Campaign name')),
                ('redemption_address', models.CharField(max_length=42, verbose_name='Redemption address')),
            ],
        ),
    ]
