# Generated by Django 5.1.7 on 2025-10-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redeem_codes', '0005_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Redeem',
            new_name='Campaign',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Redeem Address', 'verbose_name_plural': 'Redeem Addresses'},
        ),
    ]
