# Generated by Django 5.1.6 on 2025-02-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erc20_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('chain_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('version', models.CharField(max_length=12)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('db_hash', models.CharField(blank=True, default=None, max_length=64, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'DB',
            },
        ),
    ]
