# Generated by Django 5.1.7 on 2025-07-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='abi_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
