# Generated by Django 5.1.7 on 2025-07-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_update', '0002_db_abi_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='db',
            options={'verbose_name_plural': 'Database'},
        ),
    ]
