# Generated by Django 5.1.7 on 2025-08-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_update', '0003_alter_db_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='full_db_hash',
            field=models.CharField(blank=True, default=None, max_length=66, null=True, unique=True, verbose_name='DB hash'),
        ),
        migrations.AlterField(
            model_name='db',
            name='abi_url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='ABI URL'),
        ),
        migrations.AlterField(
            model_name='db',
            name='chain_url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Chains URL'),
        ),
        migrations.AlterField(
            model_name='db',
            name='erc20_url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Tokens URL'),
        ),
        migrations.AlterField(
            model_name='db',
            name='version',
            field=models.CharField(max_length=12, verbose_name='DB version'),
        ),
    ]
