# Generated by Django 5.1.7 on 2025-08-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_update', '0004_db_full_db_hash_alter_db_abi_url_alter_db_chain_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='full_db_hash',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True, verbose_name='DB hash'),
        ),
    ]
