# Generated by Django 5.1.7 on 2025-07-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
