# Generated by Django 5.1.7 on 2025-08-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_update', '0002_firmware_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='fw_hash',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True, verbose_name='Firmware hash'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='version',
            field=models.CharField(default='0.0.1', max_length=10, unique=True, verbose_name='Firmware version'),
        ),
    ]
